<?php
/**
 * ACF Field Groups
 *
 * @package Conifer
 * @version 1.0.0
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Register ACF field groups
 */
function conifer_register_acf_field_groups() {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    // Hero Section Fields
    acf_add_local_field_group(array(
        'key' => 'group_hero_section',
        'title' => 'Hero Section',
        'fields' => array(
            array(
                'key' => 'field_hero_slides',
                'label' => 'Hero Slides',
                'name' => 'hero_slides',
                'type' => 'repeater',
                'instructions' => 'Add images for the hero slider',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 1,
                'max' => 5,
                'layout' => 'table',
                'button_label' => 'Add Slide',
                'sub_fields' => array(
                    array(
                        'key' => 'field_hero_slide_image',
                        'label' => 'Slide Image',
                        'name' => 'slide_image',
                        'type' => 'image',
                        'instructions' => 'Upload an image for this slide',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_hero_slide_title',
                        'label' => 'Slide Title',
                        'name' => 'slide_title',
                        'type' => 'text',
                        'instructions' => 'Enter the title for this slide',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Enter slide title',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'front-page.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Product Fields
    acf_add_local_field_group(array(
        'key' => 'group_product_fields',
        'title' => 'Product Information',
        'fields' => array(
            array(
                'key' => 'field_product_price',
                'label' => 'Product Price',
                'name' => 'product_price',
                'type' => 'number',
                'instructions' => 'Enter the product price',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '29.99',
                'prepend' => '$',
                'append' => '',
                'min' => 0,
                'max' => '',
                'step' => '0.01',
            ),
            array(
                'key' => 'field_product_sale_price',
                'label' => 'Sale Price',
                'name' => 'product_sale_price',
                'type' => 'number',
                'instructions' => 'Enter the sale price (optional)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '19.99',
                'prepend' => '$',
                'append' => '',
                'min' => 0,
                'max' => '',
                'step' => '0.01',
            ),
            array(
                'key' => 'field_product_featured',
                'label' => 'Featured Product',
                'name' => 'product_featured',
                'type' => 'true_false',
                'instructions' => 'Check if this is a featured product',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Featured Product',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_product_bestseller',
                'label' => 'Bestseller',
                'name' => 'product_bestseller',
                'type' => 'true_false',
                'instructions' => 'Check if this is a bestseller',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Bestseller',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_product_new',
                'label' => 'New Product',
                'name' => 'product_new',
                'type' => 'true_false',
                'instructions' => 'Check if this is a new product',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33.33',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'New Product',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_product_size',
                'label' => 'Plant Size',
                'name' => 'product_size',
                'type' => 'select',
                'instructions' => 'Select the plant size',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'small' => 'Small (6-12 inches)',
                    'medium' => 'Medium (12-24 inches)',
                    'large' => 'Large (24+ inches)',
                ),
                'default_value' => array(),
                'allow_null' => 1,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_product_color',
                'label' => 'Plant Color',
                'name' => 'product_color',
                'type' => 'text',
                'instructions' => 'Enter the primary plant color',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Green, Red, Yellow, etc.',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_product_care_level',
                'label' => 'Care Level',
                'name' => 'product_care_level',
                'type' => 'select',
                'instructions' => 'Select the care difficulty level',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'easy' => 'Easy',
                    'medium' => 'Medium',
                    'hard' => 'Hard',
                ),
                'default_value' => array(),
                'allow_null' => 1,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_product_light_requirements',
                'label' => 'Light Requirements',
                'name' => 'product_light_requirements',
                'type' => 'select',
                'instructions' => 'Select the light requirements',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'full_sun' => 'Full Sun',
                    'partial_sun' => 'Partial Sun',
                    'shade' => 'Shade',
                    'indirect_light' => 'Indirect Light',
                ),
                'default_value' => array(),
                'allow_null' => 1,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_product_gallery',
                'label' => 'Product Gallery',
                'name' => 'product_gallery',
                'type' => 'gallery',
                'instructions' => 'Upload additional product images',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'insert' => 'append',
                'library' => 'all',
                'min' => 0,
                'max' => 10,
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_product_care_instructions',
                'label' => 'Care Instructions',
                'name' => 'product_care_instructions',
                'type' => 'wysiwyg',
                'instructions' => 'Enter detailed care instructions for this plant',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'product',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Testimonial Fields
    acf_add_local_field_group(array(
        'key' => 'group_testimonial_fields',
        'title' => 'Testimonial Information',
        'fields' => array(
            array(
                'key' => 'field_testimonial_author',
                'label' => 'Author Name',
                'name' => 'testimonial_author',
                'type' => 'text',
                'instructions' => 'Enter the testimonial author name',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'John Doe',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_testimonial_position',
                'label' => 'Author Position',
                'name' => 'testimonial_position',
                'type' => 'text',
                'instructions' => 'Enter the author position or title',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Plant Enthusiast',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_testimonial_rating',
                'label' => 'Rating',
                'name' => 'testimonial_rating',
                'type' => 'number',
                'instructions' => 'Enter the rating (1-5)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 5,
                'placeholder' => '',
                'prepend' => '',
                'append' => 'stars',
                'min' => 1,
                'max' => 5,
                'step' => 1,
            ),
            array(
                'key' => 'field_testimonial_featured',
                'label' => 'Featured Testimonial',
                'name' => 'testimonial_featured',
                'type' => 'true_false',
                'instructions' => 'Check if this is a featured testimonial',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Featured',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'testimonial',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    // Theme Options Fields
    acf_add_local_field_group(array(
        'key' => 'group_theme_options',
        'title' => 'Theme Options',
        'fields' => array(
            array(
                'key' => 'field_hero_title',
                'label' => 'Hero Title',
                'name' => 'hero_title',
                'type' => 'text',
                'instructions' => 'Enter the main hero title',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Welcome to Conifer',
                'placeholder' => 'Enter hero title',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_hero_subtitle',
                'label' => 'Hero Subtitle',
                'name' => 'hero_subtitle',
                'type' => 'text',
                'instructions' => 'Enter the hero subtitle',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Your trusted plant store',
                'placeholder' => 'Enter hero subtitle',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_about_text',
                'label' => 'About Text',
                'name' => 'about_text',
                'type' => 'textarea',
                'instructions' => 'Enter the about section text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                'placeholder' => 'Enter about text',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-options',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
}
add_action('acf/init', 'conifer_register_acf_field_groups');
